name = "Losers"
uuid = "1785af8d-d312-496e-9b53-daf6ddaba92c"
authors = ["Dale <djblack@uci.edu> and contributors"]
version = "0.1.0"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TestSetExtensions = "98d24dd4-01ad-11ea-1b02-c9a08f80db04"

[compat]
TestSetExtensions = "2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
