name = "Losers"
uuid = "1785af8d-d312-496e-9b53-daf6ddaba92c"
authors = ["Dale <djblack@uci.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
